"""Project scaffolding — create new repos with templates and CI/CD."""

from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path

from factory.github_client import GitHubClient
from factory.security import generate_security_policy
from factory.templates import apply_template

LOG = logging.getLogger(__name__)

CI_WORKFLOW = """\
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v4
      - run: uv sync --all-extras
      - run: uv run ruff check src/ tests/
      - run: uv run ruff format --check src/ tests/
      - run: uv run pytest tests/ -v --tb=short

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .
"""


def create_project(
    name: str,
    template: str = "fastapi",
    public: bool = False,
    description: str = "",
) -> str:
    """Create a new project repo with scaffold, CI/CD, and push.

    Returns the repo URL.
    """
    github = GitHubClient()

    # Step 1: Create the GitHub repo
    LOG.info("Creating repo: %s (public=%s)", name, public)
    repo = github._gh.get_user().create_repo(  # type: ignore[union-attr]
        name=name,
        description=description or "Built by Dark Factory",
        private=not public,
        auto_init=True,
    )
    repo_url = repo.html_url
    LOG.info("Created: %s", repo_url)

    # Step 2: Clone it locally
    with tempfile.TemporaryDirectory(prefix="df-scaffold-") as tmp:
        clone_url = f"https://{github.token}@github.com/{github.owner}/{name}.git"
        subprocess.run(
            ["git", "clone", clone_url, tmp],
            capture_output=True,
            check=True,
        )

        # Step 3: Apply template
        LOG.info("Applying template: %s", template)
        apply_template(template, tmp, variables={"PROJECT_NAME": name})

        # Step 4: Write CLAUDE.md with coding standards + security
        claude_md = Path(tmp) / "CLAUDE.md"
        claude_md.write_text(
            f"# CLAUDE.md\n\n"
            f"Project: {name}\n\n"
            f"## Build & Test\n\n"
            f"```bash\n"
            f"make develop    # Install deps\n"
            f"make test       # Run tests\n"
            f"make check      # Lint + types\n"
            f"make format     # Auto-format\n"
            f"```\n\n"
            f"## Rules\n\n"
            f"- All APIs under `/api/v1/`\n"
            f"- Tests required for all features\n"
            f"- No secrets in code\n"
            f"- Type hints on all functions\n\n"
            f"{generate_security_policy()}\n"
        )

        # Step 5: Write CI/CD workflow
        ci_dir = Path(tmp) / ".github" / "workflows"
        ci_dir.mkdir(parents=True, exist_ok=True)
        (ci_dir / "ci.yml").write_text(CI_WORKFLOW)

        # Step 6: Write README
        readme = Path(tmp) / "README.md"
        readme.write_text(
            f"# {name}\n\n"
            f"{description or 'Built by Dark Factory.'}\n\n"
            f"## Setup\n\n"
            f"```bash\n"
            f"uv sync --all-extras\n"
            f"```\n\n"
            f"## Usage\n\n"
            f"```bash\n"
            f"make develop    # install deps\n"
            f"make test       # run tests\n"
            f"make check      # lint + types\n"
            f"make dashboard  # run server\n"
            f"```\n\n"
            f"## Docker\n\n"
            f"```bash\n"
            f"docker build -t {name} .\n"
            f"docker run -p 8000:8000 {name}\n"
            f"```\n"
        )

        # Step 7: Commit and push
        subprocess.run(
            ["git", "add", "-A"],
            cwd=tmp,
            capture_output=True,
        )
        subprocess.run(
            [
                "git",
                "commit",
                "-m",
                f"feat: scaffold {name} from {template} template\n\n"
                f"Generated by Dark Factory",
            ],
            cwd=tmp,
            capture_output=True,
        )
        result = subprocess.run(
            ["git", "push", "origin", "main"],
            cwd=tmp,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            LOG.error("Push failed: %s", result.stderr)
            raise RuntimeError(f"Failed to push: {result.stderr}")

    LOG.info("Project %s ready at %s", name, repo_url)
    return repo_url
