services:
  staging:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=staging
    restart: unless-stopped

  production:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: unless-stopped
    profiles:
      - prod
